# Generated by Django 5.1.5 on 2025-04-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_page',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
